name: CI
on:
  pull_request:
    branches: [main]

# Avoids running this workflow multiple times for the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run-tests:
    uses: ./.github/workflows/test.yml
    secrets: inherit
