name: Deploy

on:
  workflow_dispatch:

# Avoids running this workflow multiple times for the same PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ secrets.vercel-env }}-${{ secrets.github-env }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ secrets.github-env }}
      vercel-env: production
      github-env: production
      # The URL where the deployment is accessible, will be shown in the Summary section of the deployment
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Sync Environment Config from Vercel
        run: vercel pull --yes --environment=${{ secrets.vercel-env }} --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project using Vercel
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      # How to set environment variables in Vercel?

      - name: Deploy Prebuilt Project
        id: deploy
        env:
          META_TAG: ${{ steps.hash_branch.outputs.digest }}-${{ github.run_number }}-${{ github.run_attempt}}
        run: |
          url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})

          echo "url=$url" >> $GITHUB_OUTPUT

      # If possible get URL of deployed service and add as comment
