name: Test

on:
  workfow_call:

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node Environment
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Check for Formatting Errors
        run: npm run fortmat

      - name: Check for ESLint Errors
        run: npm run lint

      - name: Check for Type Errors
        run: npm run typecheck

      - name: Build Project using Vercel
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: .vercel/output
          # retention-days: 30

      - uses: Run Unit Tests with Coverage Report
        run: npm run test:coverage

      - name: Upload Unit Tests Coverage Report
        if: always() # Runs always, even when tests fail
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
          # retention-days: 30

      # - name: Upload Coverage Report to Codecov
      #   uses: codecov/codecov-action@v3
      #   env:
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run End To End Tests
        run: npm run test:e2e

      - name: Upload End-to-End Tests Coverage Report
        if: always() # Runs always, even when tests fail
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          # retention-days: 30

      # - name: Send a Slack Message on Failure
      #   uses: slackapi/slack-github-action@v1.24.0
      #   if: failure()
      #   with:
      #     payload: |
      #       {
      #         "blocks": [
      #           {
      #             "type": "section",
      #             "text": {
      #               "type": "mrkdwn",
      #               "text": "🛑 *<https://github.com/${{github.repository}}/actions/runs/${{ github.run_id }}|${{ github.workflow }} workflow run>* failed."
      #             }
      #           }
      #         ]
      #       }

      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     SLACK_WEBHOOK_TYPE: ${{ secrets.SLACK_WEBHOOK_TYPE }}
